---
swagger: "2.0"
info:
  description: "This is a sample Project 15th Street server."
  version: "1.0.0"
  title: "Swagger Project 15th Street"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "Project 15th Street"
  description: "Everything about your Project 15th Street"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Example endpoint  list of Project 15th Street"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /:
    get:
      tags:
      - "Dummy View"
      summary: "Example endpoint return a message"
      description: ""
      operationId: "get"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
    post:
      tags:
      - "Dummy View"
      summary: "Example endpoint return a message"
      description: ""
      operationId: "post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
  /battery-status:
    get:
      tags:
      - "Battery View"
      summary: "Gets Battery Status"
      description: ""
      operationId: "get_battery_status"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
  /manage-vehicle:
    get:
      tags:
      - "Vehicle View"
      summary: "Manage Vehicle Charging"
      description: ""
      operationId: "manage_vehicle"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
  /set-charging-amps:
    get:
      tags:
      - "Amps View"
      summary: "Sets charging amps"
      description: ""
      operationId: "set_charging_amps"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
  /start-poll:
    get:
      tags:
      - "Poll View"
      summary: "Starts polling smart charger service"
      description: ""
      operationId: "start_poll"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
  /status-poll:
    get:
      tags:
      - "Poll View"
      summary: "Status polling smart charger service"
      description: ""
      operationId: "status_poll"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
  /stop-poll:
    get:
      tags:
      - "Poll View"
      summary: "Stops polling smart charger service"
      description: ""
      operationId: "stop_poll"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "A detail view with a message"
          schema:
            $ref: '#/definitions/dummy_msg'
      x-swagger-router-controller: "project.views.views"
definitions:
  dummy_msg:
    type: "object"
    properties:
      msg:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
