pyms:
  services:
    requests:
      data: ""
    swagger:
        path: "swagger"
        file: "swagger.yaml"
        url: "/ui/"
        project_dir: "project.views"
    tracer:
        client: "jaeger"
        host: "localhost"
        component_name: "Project 15th Street"
    metrics: true
    

  config:
    ENV: development
    DEBUG: false
    TESTING: false
    APP_NAME: Project 15th Street
    APPLICATION_ROOT: /project_15th_street
    SQLALCHEMY_TRACK_MODIFICATIONS: true
    SECRET_KEY: b'gjr39dkjn344_!67#'
    DATABASE: db.sqlite3
    SQLALCHEMY_DATABASE_URI: sqlite:///db.sqlite3
